#!/bin/bash
#SBATCH -p interactive
#SBATCH --qos nopreemption
#SBATCH --gres=gpu:1
#SBATCH -c 4
#SBATCH --mem=50G
#SBATCH --job-name=test_jupyter
#SBATCH --output=jupyter_notebook_%j.log
#SBATCH --ntasks=1
#SBATCH --time=04:00:00

date;hostname;pwd

cd $SLURM_SUBMIT_DIR
. jupyter.env
export XDG_RUNTIME_DIR=""
jupyter notebook --ip 0.0.0.0 --port 8888